# Generated by Django 5.0.1 on 2024-01-22 09:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('discount_price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('category', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=2000)),
                ('image', models.CharField(max_length=1000)),
            ],
        ),
    ]
