# Generated by Django 5.0.1 on 2024-01-31 13:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='zipcode',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxLengthValidator(12)]),
        ),
    ]
